parser_gui/apps/main_app/urls.py
from django.urls import path
from . import views

# чтобы django не путался в приложениях
app_name = 'main_app'

# если пользователь переходит в путь в первом парметре
# выполнятеся код из второго параметра
urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),  # для тестов
]

parser_gui/urls.py
from django.contrib import admin
from django.urls import path, include

# указываем место где лежат все ссылки
urlpatterns = [
    path('main_app/', include('main_app.urls')),
    path('admin/', admin.site.urls),
]

parser_gui/apps/main_app/models.py
from django.db import models

# Create your models here.

parser_gui/apps/main_app/views.py
from django.shortcuts import render


# главная страница приложения main_app
# первое что видит пользователь
def index(request):
    """Main page
    Returns:
        [render] -- [Main site's page]
    """
    return render(request, 'main_app/index.html')


# TODO выяснил что select не дает делать обычные POST, как бы это заменить
def test(request):
    """для тестирования функций
    Arguments:
        request {request} -- standart parametr
    Returns:
        render -- site's page
    """
    site = request.POST['zapros']
    return render(request, 'main_app/test.html', {'tender_site': site}) # noqa

parser_gui/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
    {% block title %}
        Главная страница
    {% endblock title %}
        </title>
</head>
<body>

    {% block content %}

    {% endblock content %}

        
    {% block internet %}
        <button type="submit">OTSOSAT</button>
    {% endblock internet %}
        
</body>
</html>

parser_gui/templates/main_app/index.html
{% extends 'base.html' %}


{% block content %}
    <h1>PAMAGITI</h1>
    <form action="{% url 'main_app:test' %}" method="POST">
        {% csrf_token %}
        <textarea name="zapros"  cols="10" rows="1" required></textarea>
        <button type="submit">Send</button>
    </form>
    <br>
{% endblock content %}

parser_gui/templates/main_app/test.html
{% extends 'base.html' %}


{% block content %}
    
    {% if tender_site %}
        <p>{{tender_site}}</p>
    {% endif %}
        
{% endblock content %}
    